name: backend
run-name: ${{ github.actor }} usando github accion como los cracks
on:
  push: 
    tags: 
     - stage
jobs:
   Connection: 
      runs-on: ubuntu-latest
      deploy:
        stages:
          - deploy
      script:
       - apt-get update
       - apt-get install -y sshpass
       - sshpass -p $CONTABO_PASSWORD ssh -o StrictHostKeyChecking=no $CONTABO_USERNAME@$CONTABO_IP "echo 'Conexión SSH establecida'"

          