name: backend
run-name: ${{ github.actor }} usando github accion como los cracks
on:
  push: 
    tags: 
     - stage
jobs:
   server: 
      runs-on: ubuntu-latest
      steps:
      - host: 66.94.96.31:16671
        with:
         username: ${{ secrets.CONTABO_USERNAME }}
         password: ${{ secrets.CONTABO_PASSWORD }}
         repository: Edusus/project-ids-backend
         tag_with_ref: true
         tag_with_sha: true

          