name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  connection:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CONTABO_IP }}
          username: ${{ secrets.CONTABO_USERNAME }}
          password: ${{ secrets.CONTABO_PASSWORD }}
  prueba: 
   runs-on: ubuntu-latest
    steps:
      - name: server
        uses: actions/checkout@v3
        with:
          ls

